[package]
name = "inventory"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "inventory"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
dashmap = "6.0.1"
